# Generated by Django 3.0.7 on 2020-06-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fav_color',
        ),
    ]
