# Generated by Django 3.0.7 on 2020-06-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['moveTime']},
        ),
    ]
