# Generated by Django 3.0.7 on 2020-06-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200628_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
